schema_version: 1

context:
  version: "2.2.1"
  python_min: "3.12"

package:
  name: mistral-vibe
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/mistral-vibe/mistral_vibe-${{ version }}.tar.gz
    sha256: a6319171fdd9929bda2e541b2fbee7d6071952e0b40e4c70cb2c694b09c7db6b

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - vibe = vibe.cli.entrypoint:main
      - vibe-acp = vibe.acp.entrypoint:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - agent-client-protocol =0.8.0
    - anyio >=4.12.0
    - cryptography >=44.0.0,<=46.0.3
    - gitpython >=3.1.46
    - giturlparse >=0.14.0
    - google-auth >=2.0.0
    - httpx >=0.28.1
    - keyring >=25.6.0
    - mcp >=1.14.0
    - mistralai =1.9.11
    - packaging >=24.1
    - pexpect >=4.9.0
    - pydantic >=2.12.4
    - pydantic-settings >=2.12.0
    - pyperclip >=1.11.0
    - python-dotenv >=1.0.0
    - pyyaml >=6.0.0
    - requests >=2.20.0
    - rich >=14.0.0
    - textual >=1.0.0
    - textual-speedups >=0.2.1
    - tomli-w >=1.2.0
    - tree_sitter >=0.25.2
    - tree-sitter-bash >=0.25.1
    - watchfiles >=1.1.1
    - zstandard >=0.25.0

tests:
  - python:
      imports:
        - vibe
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - vibe --help

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/mistralai/mistral-vibe
  summary: Minimal CLI coding agent by Mistral.

extra:
  recipe-maintainers:
    - davidbrochart
